export function isInitialized(): boolean;
export function setDynamicUserId(params: any): void;
export function validateIntegration(params: any): void;
export function init(params: any): void;
export function showRewardedVideo(params: any): void;
export function hasRewardedVideo(params: any): void;
export function showBanner(params: any): void;
export function hideBanner(params: any): void;
export function hasOfferwall(params: any): void;
export function showOfferwall(params: any): void;
export function loadBanner(params: any): void;
export function loadInterstitial(params: any): void;
export function showInterstitial(params: any): void;
export function hasInterstitial(params: any): void;
